version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py migrate &&
      if [ \"$DJANGO_ENV\" = 'development' ]; then
        python manage.py runserver 0.0.0.0:8000;
      else
        gunicorn learning_and_development.wsgi:application --bind 0.0.0.0:8000;
      fi"
    volumes:
      - ./learning_and_development:/app/learning_and_development  # Mount only the relevant folder
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load env variables from .env file

volumes:
  sqlite_data:
